### ISSUE TITLE
No fmsmd_set

### ISSUE THREAD

**Issue by seisdr** [iusmac/device_rova#6]
I don't have this file `/sys/module/radio_iris_transport/parameters/fmsmd_set` 
what kernel feature/config is necessary to get this ?

**Comment by iusmac** [comment]
Rova devices do have it. The`fmsmd_set` param is part of the QTI IRIS Transport driver.

https://github.com/iusmac/kernel_rova/blob/39855da47ded0f414e7f75d15c7779cf209d5f75/drivers/media/radio/radio-iris-transport.c#L44

**Comment by spiral009** [comment]
Oh sorry I was suppose to ask this in https://github.com/iusmac/RevampedFMRadio/issues/6
Don't know how I end up here 
But yeah `CONFIG_RADIO_IRIS=y`
